create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_de_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table group (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table group_permissao (group_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2), cidade_id bigint, cozinha_id bigint not null, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_name varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_grupos (group_id bigint not null, usuario_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table group_permissao add constraint FKpq0vwapk79os6yukly9arbbem foreign key (permissao_id) references permissao (id);
alter table group_permissao add constraint FK6qys6g68wexb9mlv350w05lbm foreign key (group_id) references group (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FKnbrdf9c9165xgwuynayr85m0h foreign key (cidade_id) references cidade (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FKojl4xuhi0atgdwom6gppw5oc4 foreign key (forma_pagamento_id) references forma_de_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table restaurante_grupos add constraint FKe3fwlkrqnq6i6mh3nwdrg6nk7 foreign key (group_id) references group (id);
alter table restaurante_grupos add constraint FKf67fo8rhjym0hllmb5mgriela foreign key (usuario_id) references usuario (id);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_de_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table group (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table group_permissao (group_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2), cidade_id bigint, cozinha_id bigint not null, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_name varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_grupos (group_id bigint not null, usuario_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table group_permissao add constraint FKpq0vwapk79os6yukly9arbbem foreign key (permissao_id) references permissao (id);
alter table group_permissao add constraint FK6qys6g68wexb9mlv350w05lbm foreign key (group_id) references group (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FKnbrdf9c9165xgwuynayr85m0h foreign key (cidade_id) references cidade (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FKojl4xuhi0atgdwom6gppw5oc4 foreign key (forma_pagamento_id) references forma_de_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table restaurante_grupos add constraint FKe3fwlkrqnq6i6mh3nwdrg6nk7 foreign key (group_id) references group (id);
alter table restaurante_grupos add constraint FKf67fo8rhjym0hllmb5mgriela foreign key (usuario_id) references usuario (id);
create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table forma_de_pagamento (id bigint not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table group (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table group_permissao (group_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table produto (ativo bit not null, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (taxa_frete decimal(38,2), cidade_id bigint, cozinha_id bigint not null, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cidade_id bigint, id bigint not null auto_increment, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_name varchar(255), endereco_numero varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null) engine=InnoDB;
create table restaurante_grupos (group_id bigint not null, usuario_id bigint not null) engine=InnoDB;
create table usuario (data_cadastro datetime not null, id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table group_permissao add constraint FKpq0vwapk79os6yukly9arbbem foreign key (permissao_id) references permissao (id);
alter table group_permissao add constraint FK6qys6g68wexb9mlv350w05lbm foreign key (group_id) references group (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FKnbrdf9c9165xgwuynayr85m0h foreign key (cidade_id) references cidade (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FKojl4xuhi0atgdwom6gppw5oc4 foreign key (forma_pagamento_id) references forma_de_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table restaurante_grupos add constraint FKe3fwlkrqnq6i6mh3nwdrg6nk7 foreign key (group_id) references group (id);
alter table restaurante_grupos add constraint FKf67fo8rhjym0hllmb5mgriela foreign key (usuario_id) references usuario (id);
