spring.application.name=jpa-exemplo

spring.datasource.url=jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=GMT-3
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate Nao cria schema
spring.jpa.hibernate.ddl-auto=validate

# ? DESLIGAR schema-generation
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/schema.sql

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=10000


spring.jackson.deserialization.fail-on-unknown-properties = true
spring.jackson.deserialization.fail-on-ignored-properties = true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.security.user.name=felipe
spring.security.user.password=1234

spring.servlet.multipart.max-file-size=20KB